image: node:latest

pages:
  stage: deploy
  script:
  - npm install -g redoc-cli
  - redoc-cli build public/index.html swagger/openapi.yaml
  artifacts:
    paths:
    - public/
  pages:
    cache:
      paths:
      - public/
    script:
      - echo "Deploying to Gitlab Pages"

