image: node:latest

pages:
  stage: deploy
  script:
  - npx @redocly/cli build-docs swagger/openapi.yaml --output=public/index.html
  #- redocly build-docs swagger/openapi.yaml --output=public/index.html
  artifacts:
    paths:
    - public
